# Generated by Django 5.1.7 on 2025-04-06 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model_used', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('chat_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatmessage')),
            ],
        ),
    ]
